export default {
  expo: {
    extra: {
      EXPO_PUBLIC_CLOUDINARY_URL: process.env.EXPO_PUBLIC_CLOUDINARY_URL,
      EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET: process.env.EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET,
      EXPO_PUBLIC_AUTH_TOKEN: process.env.EXPO_PUBLIC_AUTH_TOKEN, 
    },
  },
}; 